USE wilderness_namibia_db;

INSERT INTO experiences_camps 
    (title, subtitle, description, long_description, image_url, duration, difficulty, best_time, highlights, camps)
VALUES 
-- Cultural Experiences
('Cultural Excursions', 
 'Connect with Ancient Heritage',
 'Gain rewarding insights into the local Damara community. Visit traditional villages, learn about ancient customs, and engage with local artisans who maintain centuries-old traditions.',
 'Experience authentic cultural immersion as you visit traditional Damara villages and engage with local communities. Learn about centuries-old customs, traditional crafts, and the unique way of life in this ancient landscape. Meet local artisans, taste traditional cuisine, and hear stories passed down through generations.',
 'https://namibiawilderness-image-store.s3.us-east-1.amazonaws.com/images/doro-nawas/Wilderness-Doro-Nawas_5.jpg',
 'Half day',
 'Easy',
 'Year-round',
 'Village visits|Traditional crafts|Local cuisine|Cultural stories',
 'doro-nawas|damaraland-camp'),

('Twyfelfontein Rock Art',
 'UNESCO World Heritage Experience', 
 'Explore Namibia''s first UNESCO World Heritage Site featuring over 6,000 ancient rock engravings and paintings created by San people thousands of years ago.',
 'Journey back in time at Twyfelfontein, one of Africa''s most important rock art sites. Discover over 6,000 petroglyphs and paintings created by ancient San hunters and gatherers over thousands of years. Expert guides interpret the meanings behind these remarkable artworks, revealing stories of wildlife, hunting scenes, and spiritual beliefs. This UNESCO World Heritage Site offers profound insights into the lives of early inhabitants of the Namib Desert.',
 'https://namibiawilderness-image-store.s3.us-east-1.amazonaws.com/images/doro-nawas/Wilderness-Doro-Nawas_7.jpg',
 'Half day',
 'Moderate',
 'Year-round, cooler in winter months',
 'UNESCO World Heritage|Ancient engravings|Archaeological insights|San culture|Guided interpretation',
 'doro-nawas|damaraland-camp'),

-- Wildlife Experiences  
('Nature Drives',
 'Desert-Adapted Wildlife Tracking',
 'Combine game drives with scenic river lunches and guided walks. Track desert-adapted elephants and black rhinos while exploring the unique geology of Damaraland.',
 'Embark on expertly guided nature drives through the spectacular landscapes of Damaraland. Track desert-adapted elephants as they follow ancient migration routes, search for endangered black rhinos in rocky terrain, and observe other wildlife uniquely adapted to this harsh environment. Drives often include scenic picnic lunches by dry riverbeds and opportunities for short guided walks to examine geological formations and desert flora.',
 'https://namibiawilderness-image-store.s3.us-east-1.amazonaws.com/images/doro-nawas/Wilderness-Doro-Nawas_6.jpg',
 '3-4 hours',
 'Easy',
 'Dry season (May-October) best for wildlife',
 'Desert elephants|Black rhino tracking|Scenic lunches|Geological wonders|Expert guides',
 'doro-nawas|damaraland-camp|hoanib-skeleton-coast'),

('Desert Lion Research',
 'Conservation & Wildlife Studies',
 'Meet researchers from the Hoanib Research Centre and learn about Dr Philip Stander''s groundbreaking work with desert-adapted lions and ongoing conservation efforts.',
 'Participate in genuine conservation research at the Hoanib Research Centre. Learn about Dr Philip Stander''s decades of research on desert-adapted lions and the unique behavioral adaptations that allow these apex predators to survive in one of the world''s harshest environments. Contribute to citizen science initiatives, track wildlife movements, and gain insights into the challenges and successes of desert conservation.',
 'https://namibiawilderness-image-store.s3.us-east-1.amazonaws.com/images/hoanib-skeleton/Wilderness-Hoanib-Skeleton-Coast-Camp_4.jpg',
 '2-3 hours',
 'Moderate',
 'Year-round',
 'Desert lion research|Conservation projects|Research center visit|Wildlife tracking|Citizen science',
 'hoanib-skeleton-coast'),

-- Adventure Experiences
('Sossusvlei Dune Climbing',
 'Conquer the World''s Highest Sand Dunes',
 'Experience the thrill of climbing the iconic red dunes of Sossusvlei. Watch sunrise paint the ancient sand seas in spectacular colors as you reach summit viewpoints.',
 'Rise before dawn for an unforgettable adventure climbing the towering red dunes of Sossusvlei, some of the highest sand dunes in the world. As the sun rises, watch the dunes transform from deep crimson to brilliant orange, creating one of nature''s most spectacular displays. From the summit, panoramic views reveal the vast Namib Desert stretching endlessly to the horizon. After the climb, explore Dead Vlei''s ancient camel thorn trees, standing like dark sculptures against the white clay pan.',
 'https://namibiawilderness-image-store.s3.us-east-1.amazonaws.com/images/little-kulala/Wilderness-Little-Kulala_3.jpg',
 'Half day (early morning)',
 'Moderate to Challenging',
 'Year-round, cooler April-September',
 'Sunrise views|Big Daddy dune|Dead Vlei visit|Desert photography|Ancient landscape',
 'little-kulala'),

('Skeleton Coast Expedition',
 'Journey to the Edge of the World',
 'Explore the legendary Skeleton Coast where desert meets ocean. Discover shipwrecks, seal colonies, and the unique ecosystem of the coastal desert.',
 'Embark on a full-day expedition to one of the world''s most remote and dramatic coastlines. The Skeleton Coast earned its name from the numerous shipwrecks scattered along its treacherous shores. Witness enormous seal colonies, search for desert elephants along ephemeral rivers, and explore the unique ecosystem where cold Atlantic currents create fog banks that sustain specialized desert life. Visit abandoned diamond mining settlements and learn about the geology that created this otherworldly landscape.',
 'https://namibiawilderness-image-store.s3.us-east-1.amazonaws.com/images/hoanib-skeleton/day-excursions/1741347436974_Final-Hoanib-64.jpg',
 'Full day',
 'Moderate',
 'Year-round',
 'Historic shipwrecks|Seal colonies|Coastal desert|Desert meets ocean|Remote wilderness',
 'hoanib-skeleton-coast'),

-- Night Experiences
('Stargazing Sessions',
 'Discover the Southern Sky',
 'Look up at the cosmic ocean from dedicated stargazing decks. The clear Damaraland skies offer exceptional views of constellations and celestial phenomena.',
 'Experience the majesty of the southern hemisphere night sky from one of the world''s best stargazing locations. With virtually no light pollution, the Namib Desert offers crystal-clear views of the Milky Way, Southern Cross, and celestial wonders invisible from most of the world. Expert astronomy guides use telescopes and laser pointers to identify constellations, planets, and deep-sky objects while sharing stories of how indigenous peoples navigated by the stars.',
 'https://namibiawilderness-image-store.s3.us-east-1.amazonaws.com/images/doro-nawas/Wilderness-Doro-Nawas_8.JPG',
 'Evening',
 'Easy',
 'Year-round, best on moonless nights',
 'Dark sky viewing|Constellation tours|Telescope access|Astronomy guides|Southern Cross',
 'doro-nawas|damaraland-camp|little-kulala'),

('Scorpion Walks',
 'Desert Night Safari',
 'Discover fascinating desert critters at night using UV lights. Learn about remarkable adaptations of desert insects, arachnids, and small mammals.',
 'Join an expert guide for a thrilling nocturnal adventure discovering the desert''s hidden nightlife. Using ultraviolet torches that make scorpions glow fluorescent green, search for these fascinating arachnids and learn about their incredible adaptations to desert life. Spot dancing white lady spiders, sidewinding adders, geckos, and other creatures that emerge only after dark. This educational experience reveals the surprising diversity of life that thrives in the seemingly barren desert.',
 'https://namibiawilderness-image-store.s3.us-east-1.amazonaws.com/images/doro-nawas/Wilderness-Doro-Nawas_9.jpg',
 '1-2 hours',
 'Easy',
 'Year-round',
 'UV light exploration|Desert adaptations|Nocturnal wildlife|Conservation education|Scorpion tracking',
 'doro-nawas|damaraland-camp|little-kulala'),

-- Specialized Experiences
('Hot Air Ballooning',
 'Soar Over Ancient Deserts',
 'Begin your day before dawn with a spectacular hot air balloon flight over the red dunes of Sossusvlei and the Namib Desert.',
 'Experience the Namib Desert from a completely unique perspective on this once-in-a-lifetime hot air balloon adventure. Launch before sunrise and drift silently over the towering red dunes as the first light illuminates the ancient landscape below. From your vantage point high above, witness the interplay of light and shadow across the endless sand seas, spot desert wildlife, and capture stunning aerial photographs. The flight concludes with a champagne breakfast in the desert.',
 'https://namibiawilderness-image-store.s3.us-east-1.amazonaws.com/images/little-kulala/hot-air-balloon/02_little_kulala_sossusvlei_1593.jpg',
 'Half day (early morning)',
 'Easy',
 'April-December (weather dependent)',
 'Sunrise flight|Aerial desert views|Champagne breakfast|Professional pilots|Photography opportunities',
 'little-kulala'),

('Birding Expeditions',
 'Desert Avian Encounters',
 'Discover over 200 bird species adapted to desert conditions, including the endangered Karoo korhaan, Ludwig''s bustard, and various raptors.',
 'Join expert ornithologists to discover the remarkable birdlife of the Namib Desert. Despite the harsh conditions, over 200 species thrive here, including endemic and near-endemic species found nowhere else. Spot the endangered Karoo korhaan, massive Ludwig''s bustard, Gray''s lark, and various raptors adapted to desert hunting. Learn about the unique survival strategies of desert birds and contribute to ongoing bird monitoring programs.',
 'https://namibiawilderness-image-store.s3.us-east-1.amazonaws.com/images/hoanib-skeleton/birding/korhaan-1.jpg',
 '2-3 hours',
 'Easy',
 'Year-round, best October-March',
 'Karoo korhaan|Ludwig''s bustard|Desert raptors|Endemic species|Bird photography',
 'hoanib-skeleton-coast|doro-nawas'),

('Geological Excursions',
 'Journey Through Deep Time',
 'Explore incredible geological phenomena including ancient volcanic formations, petrified forests, and unique mineral deposits.',
 'Discover the fascinating geological history of Damaraland on guided excursions to extraordinary natural sites. Visit ancient volcanic formations, marvel at petrified forests turned to stone millions of years ago, and examine unique mineral deposits that tell the story of Earth''s evolution. Expert guides interpret the rock formations, explaining how ancient seas, volcanic activity, and erosion created this dramatic landscape. Highlights include the Organ Pipes, Burnt Mountain, and desert roses.',
 'https://namibiawilderness-image-store.s3.us-east-1.amazonaws.com/images/doro-nawas/Wilderness-Doro-Nawas_10.jpg',
 'Full day',
 'Moderate',
 'Year-round',
 'Volcanic formations|Petrified forest|Mineral specimens|Earth history|Organ Pipes|Burnt Mountain',
 'doro-nawas|damaraland-camp');
